version: '2'
services:
  helium-fast:
    image: zhuozhuang/helium-fast:1.1.3
    container_name: helium-fast
    ports:
      - "8081:8080"
    environment:
      - spring.profiles.active=prod
    restart: always

  helium-vue:
    image: helium-vue:1.1.4
    container_name: helium-vue
#    network_mode: "host"
#    depends_on:
#      - hntApi
    ports:
      - "80:80"
    restart: always
